name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/e2e/IntroTest.cy.js
          record: false
          reporter: mochawesome
          reporter-options: "{\"reportDir\":\"cypress/results\",\"overwrite\":false,\"html\":true,\"json\":true,\"timestamp\":\"mmddyyyy-HHMMss\",\"reportFilename\":\"report\",\"quiet\":true}"

      - name: Move report file to cypress/results
        run: mv cypress/reports/mochawesome.json cypress/results/report.json && npx marge cypress/results/report.json -o cypress/results
