name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          # 스펙파일 위치
          spec: cypress/e2e/IntroTest.cy.js
          # 녹화파일 생성 안함
          record: false
          # HTML 리포트 생성
          reporter: mochawesome
          reporterOptions: "{\"reportDir\":\"cypress/results\",\"overwrite\":false,\"html\":false,\"json\":true,\"timestamp\":\"mmddyyyy-HHMMss\",\"reportFilename\":\"report\",\"quiet\":true}"

      - name: Move report file to cypress/results
        run: mv cypress/mochawesome-report/mochawesome*.json cypress/results/report.json && npx marge cypress/results/report.json -o cypress/results
