name: Cypress Tests

on:
  push:
    branches:
      - master # 테스트 실행 대상 브랜치
  pull_request:
    branches:
      - master # 테스트 실행 대상 브랜치 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Cypress tests
        run: npm run cypress:run
        
      - name: Generate Cypress results
        uses: cypress-io/github-action@v2
        with:
          command: 'cypress-parallel/json-report'
          outputDir: 'cypress/results'
          
      - name: Upload Cypress Results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results/results.html
          
      - name: Cypress Run Summary
        uses: cypress-io/github-action@v2
        with:
          command: 'cypress-run-summary'
          outputDir: 'cypress/results'
          outputFormat: 'html'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

